<?php

namespace AppBundle\Repository;

/**
 * cvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cvRepository extends \Doctrine\ORM\EntityRepository
{
}
