<?php

namespace AppBundle\Repository;

/**
 * info_cvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class info_cvRepository extends \Doctrine\ORM\EntityRepository
{
}
