<?php

namespace AppBundle\Repository;

/**
 * parcourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parcourRepository extends \Doctrine\ORM\EntityRepository
{
}
