<?php

namespace AppBundle\Repository;

/**
 * parcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parcoursRepository extends \Doctrine\ORM\EntityRepository
{
}
